# Generated by Django 5.1.5 on 2025-03-29 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agency", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="executivo_registros",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="funcionarios",
            field=models.ManyToManyField(
                through="agency.Executivo_registros", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
