# Generated by Django 5.1.4 on 2025-01-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agencia",
            name="email1",
            field=models.EmailField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="e-mail 1",
            ),
        ),
        migrations.AlterField(
            model_name="agencia",
            name="email2",
            field=models.EmailField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="e-mail 2",
            ),
        ),
        migrations.AlterField(
            model_name="agencia",
            name="email3",
            field=models.EmailField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="e-mail 3",
            ),
        ),
    ]
