# Generated by Django 5.1.4 on 2025-01-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0002_alter_agencia_email1_alter_agencia_email2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agencia",
            name="bairro",
            field=models.CharField(max_length=100, null=True, verbose_name="bairro"),
        ),
        migrations.AlterField(
            model_name="agencia",
            name="cnpj",
            field=models.CharField(
                max_length=18, null=True, unique=True, verbose_name="CNPJ"
            ),
        ),
        migrations.AlterField(
            model_name="agencia",
            name="logradouro",
            field=models.CharField(
                help_text="Rua | Avenida | Alameda | Travessa",
                max_length=255,
                null=True,
                verbose_name="logradouro",
            ),
        ),
        migrations.AlterField(
            model_name="agencia",
            name="municipio",
            field=models.CharField(max_length=100, null=True, verbose_name="município"),
        ),
        migrations.AlterField(
            model_name="agencia",
            name="numero",
            field=models.CharField(max_length=10, null=True, verbose_name="número"),
        ),
        migrations.AlterField(
            model_name="agencia",
            name="uf",
            field=models.CharField(max_length=2, null=True, verbose_name="UF"),
        ),
    ]
