# Generated by Django 5.1.5 on 2025-01-31 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0002_executivo_registros"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agencia",
            name="funcionarios",
            field=models.ManyToManyField(
                through="agency.Executivo_registros", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="executivo_registros",
            name="agencia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executivo_registros",
                to="agency.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="executivo_registros",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executivo_registros",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
