# Generated by Django 5.1.5 on 2025-01-31 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0003_agencia_funcionarios_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="executivo_registros",
            old_name="data_venda",
            new_name="data_criacao",
        ),
        migrations.AlterField(
            model_name="executivo_registros",
            name="agencia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="agency.agencia"
            ),
        ),
        migrations.AlterField(
            model_name="executivo_registros",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
