# Generated by Django 5.0.6 on 2024-09-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='situacaoMensal',
            field=models.CharField(blank=True, choices=[('Mensal', 'Mensal'), ('Finalizada', 'Finalizada')], default='Mensal', max_length=10, null=True, verbose_name='Situação da venda'),
        ),
    ]
