# Generated by Django 5.0.6 on 2024-09-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeAdmin', '0002_alter_venda_situacaomensal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='nacionalidade',
            field=models.CharField(blank=True, choices=[('Americano', 'Americano'), ('Canadense', 'Canadense'), ('Mexicano', 'Mexicano'), ('Outros', 'Outros')], default='Americano', max_length=20, null=True),
        ),
    ]
