# Generated by Django 5.1.4 on 2025-02-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=101, verbose_name="nome")),
                (
                    "telefone1",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="telefone 1"
                    ),
                ),
                (
                    "telefone2",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="telefone 2"
                    ),
                ),
                (
                    "celular",
                    models.CharField(max_length=15, null=True, verbose_name="celular"),
                ),
                (
                    "email1",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="e-mail 1",
                    ),
                ),
                (
                    "email2",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="e-mail 2",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True,
                        help_text="Apenas digite os números; este campo possui autoformatação",
                        null=True,
                        verbose_name="Data de nascimento",
                    ),
                ),
                ("idade", models.IntegerField(editable=False, null=True)),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="endereço"
                    ),
                ),
                (
                    "cidade",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="cidade"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="bairro"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Estado"
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="CEP"
                    ),
                ),
                ("rg", models.CharField(max_length=20, verbose_name="RG")),
                (
                    "cpf",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                (
                    "num_passaporte",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="número de passaporte",
                    ),
                ),
                (
                    "finished_at",
                    models.DateField(null=True, verbose_name="Data finalizado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "anexo1",
                    models.FileField(
                        blank=True,
                        help_text="Envie um arquivo relacionado ao Cliente.",
                        null=True,
                        upload_to="anexos/",
                        verbose_name="Anexo",
                    ),
                ),
                (
                    "anexo2",
                    models.FileField(
                        blank=True,
                        help_text="Envie um arquivo relacionado ao Cliente.",
                        null=True,
                        upload_to="anexos/",
                        verbose_name="Anexo",
                    ),
                ),
                (
                    "anexo3",
                    models.FileField(
                        blank=True,
                        help_text="Envie um arquivo relacionado ao Cliente.",
                        null=True,
                        upload_to="anexos/",
                        verbose_name="Anexo",
                    ),
                ),
            ],
        ),
    ]
