# Generated by Django 5.1.5 on 2025-01-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="data_nascimento",
            field=models.DateField(
                blank=True,
                help_text="Apenas digite os números; este campo possui autoformatação",
                null=True,
                verbose_name="Data de nascimento",
            ),
        ),
    ]
