# Generated by Django 5.1.5 on 2025-03-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_alter_cliente_sexo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="email1",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="e-mail 1"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email2",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="e-mail 2"
            ),
        ),
    ]
