# Generated by Django 5.1.5 on 2025-01-31 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "situacaoMensal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Mensal", "Mensal"),
                            ("Finalizada", "Finalizada"),
                            ("Cancelada", "Cancelada"),
                        ],
                        default="Mensal",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("situacaoMensal_dataApoio", models.DateTimeField(auto_now_add=True)),
                ("data_venda", models.DateField(auto_now_add=True)),
                ("valor", models.FloatField()),
                (
                    "finished_at",
                    models.DateField(null=True, verbose_name="Data finalizado"),
                ),
                (
                    "nacionalidade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Americano", "Americano"),
                            ("Canadense", "Canadense"),
                            ("Mexicano", "Mexicano"),
                            ("Outros", "Outros"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "nacionalidade_outros",
                    models.CharField(
                        blank=True,
                        help_text='Especifique se você escolheu "Outros".',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tipo_cidadania",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pai para filho", "Pai para filho"),
                            ("Cônjuge", "Cônjuge"),
                            ("Avô para neto", "Avô para neto"),
                            ("Outros", "Outros"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tipo_cidadania_outros",
                    models.CharField(
                        blank=True,
                        help_text='Especifique se você escolheu "Outros".',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tipo_servico",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Vistos", "Vistos"),
                            ("Cidadania", "Cidadania"),
                            ("PID", "PID"),
                            ("Autorizações Eletrônicas", "Autorizações Eletrônicas"),
                            ("Transcrição de Casamento", "Transcrição de Casamento"),
                            ("Pesquisa de Assento", "Pesquisa de Assento"),
                            ("Passaporte", "Passaporte"),
                            ("Cartão Cidadão ", "Cartão Cidadão "),
                            ("Representação ", "Representação "),
                            ("Retirada de Documento", "Retirada de Documento"),
                            ("Agendamento de Urgencia", "Agendamento de Urgencia"),
                            ("Agendamento de Emergência", "Agendamento de Emergência"),
                            ("Identidade", "Identidade"),
                            ("Global Visa", "Global Visa"),
                            ("Atendimento Domiciliar", "Atendimento Domiciliar"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tipo_servico_outros",
                    models.CharField(
                        blank=True,
                        help_text="Digite o tido de serviço aqui.",
                        max_length=5000,
                        null=True,
                        verbose_name="Tipo de venda",
                    ),
                ),
                (
                    "tipo_pagamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Dinheiro", "Dinheiro"),
                            ("Crédito", "Crédito"),
                            ("Débito", "Débito"),
                            ("Pix", "Pix"),
                        ],
                        default="Dinheiro",
                        max_length=50,
                        null=True,
                        verbose_name="Forma de pagamento:",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="client.cliente"
                    ),
                ),
            ],
        ),
    ]
