# Generated by Django 5.1.5 on 2025-05-15 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="anexos/")),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_executivo",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Marque se o executivo estiver ativo.",
                        null=True,
                        verbose_name="Status do Executivo",
                    ),
                ),
                (
                    "situacaoMensal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Mensal", "Mensal"),
                            ("Finalizada", "Finalizada"),
                            ("Cancelada", "Cancelada"),
                        ],
                        default="Mensal",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("situacaoMensal_dataApoio", models.DateField(auto_now_add=True)),
                (
                    "Agencia_recomendada",
                    models.CharField(
                        blank=True,
                        help_text="Digite o nome da agência que recomendou.",
                        max_length=1000,
                        null=True,
                        verbose_name="Agencia Recomendada",
                    ),
                ),
                (
                    "recomendação_da_Venda",
                    models.CharField(
                        blank=True,
                        help_text="Digite o nome da pessoa que recomendou.",
                        max_length=1000,
                        null=True,
                        verbose_name="recomendação de Venda",
                    ),
                ),
                ("data_venda", models.CharField(default="15/05/2025", max_length=15)),
                (
                    "finished_at",
                    models.CharField(
                        max_length=15, null=True, verbose_name="Data finalizado"
                    ),
                ),
                (
                    "duracao_venda",
                    models.CharField(
                        default="em andamento",
                        max_length=20,
                        null=True,
                        verbose_name="Duração da venda em dias",
                    ),
                ),
                (
                    "custo_padrao_venda",
                    models.FloatField(
                        blank=True,
                        help_text="Digite o Valor padrão da venda.",
                        null=True,
                        verbose_name="Custo da Venda",
                    ),
                ),
                ("valor", models.FloatField(blank=True, null=True)),
                (
                    "desconto",
                    models.FloatField(
                        blank=True,
                        help_text="Digite o valor do desconto para a venda.",
                        null=True,
                    ),
                ),
                (
                    "custo_sobre_venda",
                    models.FloatField(
                        blank=True,
                        help_text="Digite o custo sobre a venda.",
                        null=True,
                        verbose_name="Custo sobre Venda",
                    ),
                ),
                (
                    "nacionalidade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Americano", "Americano"),
                            ("Canadense", "Canadense"),
                            ("Mexicano", "Mexicano"),
                            ("Outros", "Outros"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "nacionalidade_outros",
                    models.CharField(
                        blank=True,
                        help_text='Especifique se você escolheu "Outros".',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tipo_cidadania",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pai para filho", "Pai para filho"),
                            ("Cônjuge", "Cônjuge"),
                            ("Avô para neto", "Avô para neto"),
                            ("Outros", "Outros"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tipo_cidadania_outros",
                    models.CharField(
                        blank=True,
                        help_text='Especifique se você escolheu "Outros".',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "vistos",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Americano", "Americano"),
                            ("Canadense", "Canadense"),
                            ("Mexicano", "Mexicano"),
                            ("Outros", "Outros"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "vistos_outros",
                    models.CharField(
                        blank=True,
                        help_text='Especifique se você escolheu "Outros".',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tipo_servico",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Vistos", "Vistos"),
                            ("Cidadania", "Cidadania"),
                            ("PID", "PID"),
                            ("Autorizações Eletrônicas", "Autorizações Eletrônicas"),
                            ("Transcrição de Casamento", "Transcrição de Casamento"),
                            ("Pesquisa de Assento", "Pesquisa de Assento"),
                            ("Passaporte", "Passaporte"),
                            ("Cartão Cidadão ", "Cartão Cidadão "),
                            ("Representação ", "Representação "),
                            ("Retirada de Documento", "Retirada de Documento"),
                            ("Agendamento de Urgencia", "Agendamento de Urgencia"),
                            ("Agendamento de Emergência", "Agendamento de Emergência"),
                            ("Identidade", "Identidade"),
                            ("Global Visa", "Global Visa"),
                            ("Atendimento Domiciliar", "Atendimento Domiciliar"),
                            (
                                "Serviços para brasileiros residentes no exterior",
                                "Serviços para brasileiros residentes no exterior",
                            ),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tipo_servico_outros",
                    models.CharField(
                        blank=True,
                        help_text="Digite o tido de serviço aqui.",
                        max_length=5000,
                        null=True,
                        verbose_name="Tipo de venda",
                    ),
                ),
                (
                    "tipo_pagamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Dinheiro", "Dinheiro"),
                            ("Crédito", "Crédito"),
                            ("Débito", "Débito"),
                            ("Pix", "Pix"),
                        ],
                        default="Dinheiro",
                        max_length=50,
                        null=True,
                        verbose_name="Forma de pagamento:",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="client.cliente"
                    ),
                ),
            ],
        ),
    ]
