# Generated by Django 5.1.5 on 2025-03-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venda",
            name="data_venda",
            field=models.CharField(default="29/03/2025", max_length=15),
        ),
    ]
