# Generated by Django 5.1.5 on 2025-01-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_alter_venda_vendedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="duracao_venda",
            field=models.DateField(null=True, verbose_name="Duração da venda"),
        ),
    ]
