# Generated by Django 5.1.5 on 2025-03-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_venda_executivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="status_executivo",
            field=models.BooleanField(
                default=False,
                help_text="Marque se o executivo estiver ativo.",
                verbose_name="Status do Executivo",
            ),
        ),
    ]
