# Generated by Django 5.1.5 on 2025-03-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_venda_status_executivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venda",
            name="status_executivo",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Marque se o executivo estiver ativo.",
                null=True,
                verbose_name="Status do Executivo",
            ),
        ),
    ]
