# Generated by Django 5.1.5 on 2025-01-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_alter_venda_duracao_venda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venda",
            name="duracao_venda",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Duração da venda em dias"
            ),
        ),
    ]
