# Generated by Django 5.1.5 on 2025-01-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0006_alter_venda_duracao_venda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venda",
            name="situacaoMensal_dataApoio",
            field=models.DateField(auto_now_add=True),
        ),
    ]
