# Generated by Django 5.1.4 on 2025-01-15 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="primeiro nome"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="último nome"),
                ),
                ("nome", models.CharField(editable=False, max_length=101, null=True)),
                ("idade", models.IntegerField(editable=False, null=True)),
                (
                    "username",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="apelido"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="e-mail"
                    ),
                ),
                ("tefone", models.CharField(max_length=15)),
                ("salario", models.FloatField(default=0, verbose_name="salário")),
                (
                    "comissao_acumulada",
                    models.FloatField(default=0, verbose_name="comissão acumulada"),
                ),
                ("telefone", models.CharField(blank=True, max_length=15)),
                ("cidade", models.CharField(max_length=255, null=True)),
                (
                    "data_nascimento",
                    models.DateField(null=True, verbose_name="Data de nascimento"),
                ),
                ("token", models.CharField(max_length=8, null=True, unique=True)),
                ("is_staff", models.BooleanField(default=True)),
                (
                    "cpf",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                (
                    "departamento",
                    models.CharField(
                        choices=[
                            ("Adm", "Administrativo"),
                            ("Vend", "Vendedor"),
                            ("Exec", "Executivo"),
                        ],
                        default="Adm",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "atividade",
                    models.CharField(
                        choices=[("Ativo", "Ativo "), ("Inativo", "Inativo")],
                        default="Ativo",
                        max_length=15,
                        null=True,
                        verbose_name="",
                    ),
                ),
                (
                    "especializacao_funcao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Financeiro", "Financeiro"),
                            ("Despachante", "Despachante "),
                            ("Despachante externo", "Despachante externo "),
                            ("Suporte Whatsapp", "Suporte Whatsapp"),
                            ("Executivo contas", "Executivo contas"),
                        ],
                        default="",
                        help_text="A função a qual o empregado exerce é:",
                        max_length=100,
                        null=True,
                        verbose_name="especialização",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="customuser_set",
                        related_query_name="customuser",
                        to="auth.group",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="customuser_set",
                        related_query_name="customuser",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
    ]
