# Generated by Django 5.1.4 on 2025-01-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="Sub_salario_fixo",
            field=models.FloatField(
                default=0,
                help_text="Um valor fixo pago ao funcionario",
                verbose_name="salário fixo",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="atividade",
            field=models.CharField(
                choices=[("Ativo", "Ativo "), ("Inativo", "Inativo")],
                default="Ativo",
                help_text="Defini se o funcionario tá ativo na empresa, ou foi desligado.",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="cpf",
            field=models.CharField(
                max_length=14, null=True, unique=True, verbose_name="CPF"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="especializacao_funcao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Financeiro", "Financeiro"),
                    ("Despachante", "Despachante "),
                    ("Despachante externo", "Despachante externo "),
                    ("Suporte Whatsapp", "Suporte Whatsapp"),
                    ("Executivo contas", "Executivo contas"),
                ],
                default="",
                help_text="A função a qual o empregado exerce.",
                max_length=100,
                null=True,
                verbose_name="especialização, área de atuação",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="salario",
            field=models.FloatField(
                default=0, editable=False, verbose_name="salário total"
            ),
        ),
    ]
