# Generated by Django 5.1.4 on 2025-01-23 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
        ("worker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funcionario",
            name="tefone",
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="email",
            field=models.EmailField(max_length=255, unique=True, verbose_name="e-mail"),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="especializacao_funcao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Financeiro", "Financeiro"),
                    ("Despachante", "Despachante "),
                    ("Despachante externo", "Despachante externo "),
                    ("Suporte Whatsapp", "Suporte Whatsapp"),
                    ("Executivo contas", "Executivo contas"),
                ],
                default="",
                help_text="A função a qual o empregado exerce.",
                max_length=100,
                null=True,
                verbose_name="especialização",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="telefone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="Executivo_registros",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("data_venda", models.DateTimeField(auto_now_add=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendas",
                        to="agency.agencia",
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
