# Generated by Django 5.1.5 on 2025-04-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contasmensal",
            name="entrada",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contasmensal",
            name="saida",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
