# Generated by Django 5.1.5 on 2025-03-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="especializacao_funcao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Financeiro", "Financeiro"),
                    ("Despachante", "Despachante "),
                    ("Despachante externo", "Despachante externo "),
                    ("Suporte Whatsapp", "Suporte Whatsapp"),
                    ("Executivo contas", "Executivo contas"),
                    (
                        "Despachante externo e Executivo contas",
                        "Despachante externo e Executivo contas",
                    ),
                    ("Diretor(a)", "Diretor(a)"),
                ],
                default="Financeiro",
                help_text="A função a qual o empregado exerce.",
                max_length=100,
                null=True,
                verbose_name="especialização, área de atuação",
            ),
        ),
    ]
