# Generated by Django 5.1.5 on 2025-04-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0002_alter_contasmensal_entrada_alter_contasmensal_saida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contasmensal",
            name="entrada",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="contasmensal",
            name="saida",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
