# Generated by Django 5.1.4 on 2025-01-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0002_funcionario_sub_salario_fixo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="especializacao_funcao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Financeiro", "Financeiro"),
                    ("Despachante", "Despachante "),
                    ("Despachante externo", "Despachante externo "),
                    ("Suporte Whatsapp", "Suporte Whatsapp"),
                    ("Executivo contas", "Executivo contas"),
                ],
                default="Financeiro",
                help_text="A função a qual o empregado exerce.",
                max_length=100,
                null=True,
                verbose_name="especialização, área de atuação",
            ),
        ),
    ]
