# Generated by Django 5.1.4 on 2025-01-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0003_alter_funcionario_especializacao_funcao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="Sub_salario_fixo",
            field=models.FloatField(
                blank=True,
                default=0,
                help_text="Um valor fixo pago ao funcionario",
                null=True,
                verbose_name="salário fixo",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="atividade",
            field=models.CharField(
                blank=True,
                choices=[("Ativo", "Ativo "), ("Inativo", "Inativo")],
                default="Ativo",
                help_text="Defini se o funcionario tá ativo na empresa, ou foi desligado.",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="cidade",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=14, null=True, unique=True, verbose_name="CPF"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="data_nascimento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de nascimento"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="departamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Adm", "Administrativo"),
                    ("Vend", "Vendedor"),
                    ("Exec", "Executivo"),
                ],
                default="Adm",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
