# Generated by Django 5.1.5 on 2025-04-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0003_alter_contasmensal_entrada_alter_contasmensal_saida"),
    ]

    operations = [
        migrations.AddField(
            model_name="fluxomensal",
            name="subtotal_liquido",
            field=models.FloatField(blank=True, null=True, verbose_name="Sub Líquido"),
        ),
        migrations.AddField(
            model_name="fluxomensal",
            name="total_liquido",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Total Líquido"
            ),
        ),
    ]
