# Generated by Django 5.1.4 on 2025-01-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0004_alter_funcionario_sub_salario_fixo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="cpf",
            field=models.CharField(max_length=14, unique=True, verbose_name="CPF"),
        ),
    ]
