# Generated by Django 5.1.4 on 2025-01-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0005_alter_funcionario_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="cpf",
            field=models.CharField(
                max_length=14, null="True", unique=True, verbose_name="CPF"
            ),
        ),
    ]
