# Generated by Django 5.0.6 on 2024-09-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homeAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroEspelho',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('homeAdmin.cadcliente',),
        ),
        migrations.CreateModel(
            name='CustomUser_FuncionarioEspelho',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('homeAdmin.customuser_funcionario',),
        ),
        migrations.CreateModel(
            name='VendaEspelho',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('homeAdmin.venda',),
        ),
    ]
